/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import Form.SuratPindah.*;
import com.jtattoo.plaf.smart.SmartLookAndFeel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Arya Wicaksana
 */
public class CetakSP35 extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form CetakSP36
     */
    public void cetak(){
        PrinterJob pj = PrinterJob.getPrinterJob();
pj.setJobName("nama_");
pj.setCopies(1);
PageFormat format = pj.defaultPage();
format.setOrientation(PageFormat.PORTRAIT);

pj.setPrintable(new Printable() {
public int print(Graphics pg, PageFormat pf, int pageNum){
if (pageNum > 0){
return Printable.NO_SUCH_PAGE;
}
Graphics2D g2 = (Graphics2D) pg;
g2.translate(pf.getImageableX(), pf.getImageableY());
jLayeredPane2.paint(g2);
return Printable.PAGE_EXISTS;
}
});
if (pj.printDialog() == false)
return;

try {
        pj.print();
  } catch (PrinterException ex) {
        // handle exception
  }   
    }

              
        private void isiOtomatisAtas(){
            lbl_no_surat.setText(SuratPindah.txt_no_surat_pindah.getText());
        }
    
        private void isiOtomatisDDA(){
            lbl_no_kk_dda.setText(SuratPindah.txt_no_kk_dda.getText());
            lbl_nama_kepala_keluarga_dda.setText(SuratPindah.txt_nama_kepala_keluarga.getText());
            lbl_alamat.setText(SuratPindah.lbl_alamat_dda.getText());
            lbl_nik_dda.setText(SuratPindah.txt_nik_dda.getText());
            lbl_nama_dda.setText(SuratPindah.lbl_nama_dda.getText());
        }
        
        private void isiOtomatisDKP(){
            lbl_alamat_tujuan_pindah.setText(SuratPindah.txt_alamat_tujuan_pindah_dkp.getText());
            lbl_tgl_sekarang.setText(MenuUtama.lblTanggal.getText());
        }
        
        private void JumlahYangPindah(){
            try {
                String x = SuratPindah.lbl_id_daftar_kyp.getText();
                String sql = "SELECT COUNT(*) FROM keluarga_yang_pindah where id_daftar_kyp = '"+x+"' ";
           pst=conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                lbl_jumlah_pindah.setText(rs.getString(1));
            }
       }
catch (Exception e)
{   System.out.println(e);
}
        }
        
        
    public CetakSP35() {
        initComponents();
        conn = KoneksiDB.ConnectDb(); 
        isiOtomatisAtas();
        isiOtomatisDDA();
        isiOtomatisDKP();
        JumlahYangPindah();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbl_alamat = new javax.swing.JLabel();
        lbl_alamat_tujuan_pindah = new javax.swing.JLabel();
        lbl_nama_kepala_keluarga_dda = new javax.swing.JLabel();
        lbl_no_kk_dda = new javax.swing.JLabel();
        lbl_no_surat = new javax.swing.JLabel();
        lbl_nama_dda = new javax.swing.JLabel();
        lbl_nik_dda = new javax.swing.JLabel();
        lbl_tgl_sekarang = new javax.swing.JLabel();
        lbl_jumlah_pindah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_alamat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_alamat.setText("lbl_alamat");
        jLayeredPane2.add(lbl_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 220, 30));

        lbl_alamat_tujuan_pindah.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_alamat_tujuan_pindah.setText("lbl_alamat_tujuan_pindah");
        lbl_alamat_tujuan_pindah.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLayeredPane2.add(lbl_alamat_tujuan_pindah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 210, 20));

        lbl_nama_kepala_keluarga_dda.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_nama_kepala_keluarga_dda.setText("lbl_nama_kepala_keluarga_dda");
        jLayeredPane2.add(lbl_nama_kepala_keluarga_dda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 190, 30));

        lbl_no_kk_dda.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_no_kk_dda.setText("lbl_no_kk_dda");
        lbl_no_kk_dda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLayeredPane2.add(lbl_no_kk_dda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 200, 20));

        lbl_no_surat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_no_surat.setText("lbl_no_surat");
        jLayeredPane2.add(lbl_no_surat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 10));

        lbl_nama_dda.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_nama_dda.setText("lbl_nama_dda");
        jLayeredPane2.add(lbl_nama_dda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 220, 20));

        lbl_nik_dda.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_nik_dda.setText("lbl_nik_dda");
        jLayeredPane2.add(lbl_nik_dda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 200, 20));

        lbl_tgl_sekarang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_tgl_sekarang.setText("lbl_tgl_sekarang");
        jLayeredPane2.add(lbl_tgl_sekarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 593, 110, 20));

        lbl_jumlah_pindah.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_jumlah_pindah.setText("xxxx");
        jLayeredPane2.add(lbl_jumlah_pindah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1.35 kecil.jpg"))); // NOI18N
        jLayeredPane2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        jMenu2.setText("File");

        jMenuItem1.setText("Print");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        cetak();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         { 
        String ObjButtons[] = {"Ya","Tidak"};
        int PromptResult = JOptionPane.showOptionDialog(null,"Apakah Anda ingin menutup Cetak Surat Pindah F-1.35?","[ PENTING ]",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(PromptResult==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_alamat_tujuan_pindah;
    private javax.swing.JLabel lbl_jumlah_pindah;
    private javax.swing.JLabel lbl_nama_dda;
    private javax.swing.JLabel lbl_nama_kepala_keluarga_dda;
    private javax.swing.JLabel lbl_nik_dda;
    private javax.swing.JLabel lbl_no_kk_dda;
    private javax.swing.JLabel lbl_no_surat;
    private javax.swing.JLabel lbl_tgl_sekarang;
    // End of variables declaration//GEN-END:variables
}
