/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import static Form.MenuUtama.desktopPane;
import java.awt.Font;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Arya Wicaksana
 */
public class KeluargaYangPindah extends javax.swing.JInternalFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form KeluargaYangPindah
     */

    private void bersih(){
        
        txt_nama_kyp.setText("");
        txt_nik_kyp.setText("");
        txt_no_kyp.setText("");
        txt_shdk_kyp.setText("");
        tgl_masa_berlaku_ktp_kyp.setDate(null);
    }
    
   private void id_kyp_siap(){
          try
       {
            String Sql = "select max(id_kyp) from keluarga_yang_pindah";
            pst=conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                lbl_id_kyp.setText(rs.getString(1));
                int value1 =  Integer.parseInt(lbl_id_kyp.getText());
                int value2 = value1+1;
                String siap = Integer.toString(value2);
                lbl_id_kyp.setText(siap);
            }
       }
catch (Exception e)
{String kyp;
        kyp="1";
    lbl_id_kyp.setText(kyp);
    System.out.println(e);
}    
}    
            
        private void lebarKolom(){ 
        TableColumn column;
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTable1.getColumnModel().getColumn(0); 
        column.setPreferredWidth(29);
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(130); 
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(140); 
        column = jTable1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(140); 
        column = jTable1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(53);
        column = jTable1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(140); 
        column = jTable1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(53);
    }

        private void UpdateTabelKYP(){
            //String z = DapatkanId_daftar_kyp.lbl_id_daftar_kyp.getText();
            String z = lbl_id_daftar_kyp.getText();
            try
        {
            //String sql = "SELECT * FROM keluarga_yang_pindah where id_daftar_kyp = '"+z+"' ";
            String sql = "select id_kyp as 'ID KyP', no_kyp as 'No.Urut',"
                    + " nik_kyp as 'NIK', nama_kyp as 'Nama', "
                    + "masa_berlaku_ktp_kyp as 'Masa berlaku KTP', shdk_kyp as 'SHDK',"
                    + " id_daftar_kyp as 'ID Daftar KyP' from keluarga_yang_pindah"
                    + " where id_daftar_kyp = '"+z+"' ";
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
catch (Exception e)
{
    JOptionPane.showMessageDialog(null, e);
}
}
      
    private void batasanInput(){
        txt_nik_kyp.setDocument(new batasInput((byte)16).getOnlyNumber(txt_nik_kyp));
        txt_no_kyp.setDocument(new batasInput((byte)2).getOnlyNumber(txt_no_kyp));
    }
        
    public KeluargaYangPindah() {
        initComponents();
        conn = KoneksiDB.ConnectDb(); 
        jTable1.getTableHeader().setFont(new Font("SansSerif", 0 , 8));
        lbl_id_daftar_kyp.setText(DapatkanId_daftar_kyp.lbl_bakal_id_daftar_kyp.getText());
        id_kyp_siap();
        lebarKolom();
        UpdateTabelKYP();
        batasanInput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tgl_masa_berlaku_ktp_kyp = new com.toedter.calendar.JDateChooser();
        txt_nama_kyp = new javax.swing.JTextField();
        txt_nik_kyp = new javax.swing.JTextField();
        txt_shdk_kyp = new javax.swing.JTextField();
        btn_tambahkan_kyp = new javax.swing.JButton();
        btn_perbarui_kyp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_id_daftar_kyp = new javax.swing.JLabel();
        btn_lanjut_kyp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_no_kyp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbl_id_kyp = new javax.swing.JLabel();
        btn_hapus_kyp = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "NIK", "Nama", "Masa Berlaku KTP S/D", "SHDK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel6.setText("id kyp :");

        jLabel7.setText("NIK :");

        jLabel8.setText("Nama :");

        jLabel9.setText("Masa Berlaku KTP S/D :");

        jLabel11.setText("SHDK :");

        tgl_masa_berlaku_ktp_kyp.setDateFormatString("yyyy-MM-dd");

        txt_shdk_kyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_shdk_kypActionPerformed(evt);
            }
        });

        btn_tambahkan_kyp.setText("Tambahkan");
        btn_tambahkan_kyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahkan_kypActionPerformed(evt);
            }
        });

        btn_perbarui_kyp.setText("Perbarui");
        btn_perbarui_kyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbarui_kypActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SFNS Display", 0, 36)); // NOI18N
        jLabel1.setText("Keluarga yang Pindah (kyp)");

        jLabel2.setText("id daftar kyp :");

        lbl_id_daftar_kyp.setText("XXX");

        btn_lanjut_kyp.setText("Lanjutkan");
        btn_lanjut_kyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lanjut_kypActionPerformed(evt);
            }
        });

        jLabel3.setText("No.kyp :");

        txt_no_kyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_kypActionPerformed(evt);
            }
        });

        jButton1.setText("Kosongkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_id_kyp.setText("xxxxx");

        btn_hapus_kyp.setText("Hapus");
        btn_hapus_kyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_kypActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_lanjut_kyp))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_shdk_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_masa_berlaku_ktp_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nik_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nama_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_id_daftar_kyp)
                                    .addComponent(txt_no_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_id_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_tambahkan_kyp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_perbarui_kyp)
                                .addGap(79, 79, 79)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_hapus_kyp)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_id_daftar_kyp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_id_kyp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_no_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nik_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nama_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tgl_masa_berlaku_ktp_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_shdk_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambahkan_kyp)
                    .addComponent(btn_perbarui_kyp)
                    .addComponent(jButton1)
                    .addComponent(btn_hapus_kyp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_lanjut_kyp)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bersih();
        id_kyp_siap();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_no_kypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_kypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_kypActionPerformed

    private void btn_perbarui_kypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbarui_kypActionPerformed
        // TODO add your handling code here:
        try
        {
            int value1 = Integer.parseInt(lbl_id_kyp.getText());
            int value2 = Integer.parseInt(txt_no_kyp.getText());
            String value3 = txt_nik_kyp.getText();
            String value4 = txt_nama_kyp.getText();
            String value5 = tgl_masa_berlaku_ktp_kyp.getDateFormatString();
            String value6 = txt_shdk_kyp.getText();
            int value7 = Integer.parseInt(lbl_id_daftar_kyp.getText());
            
            String sql="update keluarga_yang_pindah set id_kyp='"+value1+"', no_kyp='"+value2+"', "
                    + "nik_kyp='"+value3+"', nama_kyp='"+value4+"', masa_berlaku_ktp_kyp='"+value5+"', "
                    + "shdk_kyp='"+value6+"', id_daftar_kyp='"+value7+"' where id_kyp= '"+value1+"' ";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data telah diubah.","[ SUKSES ]",1);
            UpdateTabelKYP();
            lebarKolom();
            btn_perbarui_kyp.setFont(new java.awt.Font("Tahoma", 0, 11));
            btn_perbarui_kyp.setText("Perbarui");
            btn_tambahkan_kyp.setEnabled(true);
            btn_lanjut_kyp.setEnabled(true);
            
            
        }
        catch (Exception e){
        }
    }//GEN-LAST:event_btn_perbarui_kypActionPerformed

    private void btn_tambahkan_kypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahkan_kypActionPerformed
        // TODO add your handling code here:
        try
        {
            String Sql = "insert into keluarga_yang_pindah (id_kyp, no_kyp, nik_kyp, nama_kyp, "
                    + "masa_berlaku_ktp_kyp, shdk_kyp, id_daftar_kyp) "
                    + "values (?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(Sql);

            pst.setInt(1, 0);
            pst.setInt(2, Integer.parseInt(txt_no_kyp.getText()));
            pst.setString(3, txt_nik_kyp.getText());
            pst.setString(4, txt_nama_kyp.getText());
            pst.setString(5, ((JTextField)tgl_masa_berlaku_ktp_kyp.getDateEditor().getUiComponent()).getText());
            pst.setString(6, txt_shdk_kyp.getText());
            pst.setInt(7, Integer.parseInt(lbl_id_daftar_kyp.getText()));

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan.","[ SUKSES ]",1);
            UpdateTabelKYP();
            id_kyp_siap();
            btn_lanjut_kyp.setEnabled(true);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Penambahan data ke tabel SQL : Error");
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_tambahkan_kypActionPerformed

    private void txt_shdk_kypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_shdk_kypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_shdk_kypActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        btn_perbarui_kyp.setFont(new java.awt.Font("Tahoma", 1, 12));
        btn_perbarui_kyp.setText("Simpan Perubahan");
        btn_tambahkan_kyp.setEnabled(false);
        btn_lanjut_kyp.setEnabled(false);

        try{
            int row = jTable1.getSelectedRow();
            String Table_click = (jTable1.getModel().getValueAt(row, 0).toString());
            String sql= "select * from keluarga_yang_pindah where id_kyp='"+Table_click+"' ";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()) {
                String add0= rs.getString("id_kyp");
                lbl_id_kyp.setText(add0);
                String add1= rs.getString("no_kyp");
                txt_no_kyp.setText(add1);
                String add2= rs.getString("nik_kyp");
                txt_nik_kyp.setText(add2);
                String add3= rs.getString("nama_kyp");
                txt_nama_kyp.setText(add3);
                String add4= rs.getString("masa_berlaku_ktp_kyp");
                tgl_masa_berlaku_ktp_kyp.setDateFormatString(add4);
                String add5= rs.getString("shdk_kyp");
                txt_shdk_kyp.setText(add5);
                String add6= rs.getString("id_daftar_kyp");
                lbl_id_daftar_kyp.setText(add6);
            }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_lanjut_kypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lanjut_kypActionPerformed
        // TODO add your handling code here:
         int p = JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk melanjutkan? " +
                 "Pastikan data-data yang sudah anda isikan sudah valid", "Lanjutkan?", JOptionPane.YES_NO_OPTION);
        if (p==0){
        SuratPindah k = new SuratPindah();
        desktopPane.add(k);
        k.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_btn_lanjut_kypActionPerformed

    private void btn_hapus_kypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_kypActionPerformed
        // TODO add your handling code here:
        {
            String ObjButtons[] = {"Ya","Tidak"};
            int PromptResult = JOptionPane.showOptionDialog(null,"Apakah Anda ingin menghapus data yang anda pilih?","[ PENTING ]",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
            if(PromptResult==JOptionPane.YES_OPTION)
            {
                try {
                    String sql = "delete from keluarga_yang_datang where id_kyd=?";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, lbl_id_kyp.getText());
                    pst.execute();

                    JOptionPane.showMessageDialog(null, "Terhapus.","[ SUKSES ]",1);
                    UpdateTabelKYP();

                    bersih();

                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }

            }
            else {};
        }
    }//GEN-LAST:event_btn_hapus_kypActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus_kyp;
    private javax.swing.JButton btn_lanjut_kyp;
    private javax.swing.JButton btn_perbarui_kyp;
    private javax.swing.JButton btn_tambahkan_kyp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public static javax.swing.JLabel lbl_id_daftar_kyp;
    public static javax.swing.JLabel lbl_id_kyp;
    private com.toedter.calendar.JDateChooser tgl_masa_berlaku_ktp_kyp;
    public static javax.swing.JTextField txt_nama_kyp;
    public static javax.swing.JTextField txt_nik_kyp;
    public static javax.swing.JTextField txt_no_kyp;
    public static javax.swing.JTextField txt_shdk_kyp;
    // End of variables declaration//GEN-END:variables
}
