/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lapPembelian.java
 *
 * Created on Nov 10, 2015, 9:29:47 PM
 */
package Form;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author novika
 */
public class lapDataPendaftar extends javax.swing.JInternalFrame {
java.sql.Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /** Creates new form lapPembelian */
    public lapDataPendaftar() {
        initComponents();
        conn = KoneksiDB.ConnectDb();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCari = new javax.swing.JButton();
        cbdesakelurahan = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Laporan Data Pendaftar");

        btnCari.setText("View");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        cbdesakelurahan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cbdesakelurahan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gilingsari ", "Guntur ", "Joho ", "Lungge ", "Mudal ", "Nampirejo", "Banyuurip ", "Butuh ", "Giyanti ", "Jampirejo ", "Jampiroso ", "Jurang ", "Kebonsari ", "Kertosari ", "Kowangan ", "Madureso ", "Manding ", "Mungseng ", "Purworejo ", "Sidorejo ", "Temanggung I ", "Temanggung II ", "Tlogorejo ", "Walitelon Selatan ", "Walitelon Utara" }));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Desa/Kelurahan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnCari))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addGap(40, 40, 40)
                        .addComponent(cbdesakelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbdesakelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnCari)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
       try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/kependudukan1";
            Connection cn = (Connection) DriverManager.getConnection(url, "root", "");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String x = (String) cbdesakelurahan.getSelectedItem();
            System.out.println(x);
         
            String SQL = "SELECT * FROM `pendaftar` where desakelurahan_pendaftar='"+x+"' ";
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            JasperPrint jasperPrint;
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperReport jasperReport = JasperCompileManager.compileReport(System.getProperties().getProperty("java.class.path").split(";")[System.getProperties().getProperty("java.class.path").split(";").length - 1] + "/Laporan/lapPendaftar.jrxml");
            jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            //viewer.setTitle(".: Jasper Report :.");
            viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(470, 30, screenSize.width, screenSize.height);
            viewer.setSize(900, 700);
            viewer.setTitle(" Laporan Loket I - Data Pendaftar ");
            viewer.setVisible(true);

            st.close();
            cn.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        /*try {
        String cb = (String) cbdesakelurahan.getSelectedItem();
        String SQL = "SELECT * FROM `pendaftar` order by '"+cb+"'  ";
        String report="D:\\Documents\\NetBeansProjects\\APPPPPSK Kec Temanggung\\src\\Laporan\\pendaftar.jrxml";
        
        JasperReport jr=JasperCompileManager.compileReport(report);
        JasperPrint jp=JasperFillManager.fillReport(jr, null, conn);
        JasperViewer.viewReport(jp, false);
        
        } catch (Exception e) {
        System.out.println(e);
        }*/
    }//GEN-LAST:event_btnCariActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JComboBox cbdesakelurahan;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
