/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

/**
 *
 * @author Arya Wicaksana
 */
public class Login extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Login
     */
    
public void KirimDataLoginKeMenuUtama(){
    String t1;
    t1 = txtidpengguna.getText();
    int idpengguna = Integer.parseInt(t1);
    MenuUtama.idpengguna = idpengguna;
    MenuUtama.jabatan = (String) cmbjabatan.getSelectedItem();
    Pendaftar.idpengguna = idpengguna;
    Pendaftar.jabatan = (String) cmbjabatan.getSelectedItem();
    Pendaftaran.idpengguna = idpengguna;
    Pendaftaran.jabatan = (String) cmbjabatan.getSelectedItem();
}

    private void AksesLogin() {
         String SQL = "select * from pengguna where id_pengguna=? and password=? and jabatan=?";
        try {
            pst=conn.prepareStatement(SQL);
            
            pst.setString(1, txtidpengguna.getText());
            pst.setString(2, txtpassword.getText());
            pst.setString(3, (String) cmbjabatan.getSelectedItem());
            
            rs=pst.executeQuery();
            
            if (rs.next()) {
                 this.dispose();
                 KirimDataLoginKeMenuUtama();
                 new MenuUtama().setVisible(true);
               
            }
            else{
               JOptionPane.showMessageDialog(null, "Maaf, informasi anda tidak"
                       + " dikenali sistem.\nHarap periksa id , password , "
                       + "dan Jabatan", "[ PENTING ]",2); 
            }
            
        } catch (Exception e) {
        }
    }
    
      public Login() {
        initComponents();
        conn = KoneksiDB.ConnectDb();
        setLocationRelativeTo(null);
        txtidpengguna.setDocument(new batasInput((byte)2).getOnlyNumber(txtidpengguna));
        ImageIcon ico = new ImageIcon("src\\Gambar\\book.png");
        setIconImage(ico.getImage());
        setTitle("Login");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        cmbjabatan = new javax.swing.JComboBox();
        btnlogin = new javax.swing.JButton();
        txtidpengguna = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        ket = new javax.swing.JLabel();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbjabatan.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Petugas", "Admin" }));
        cmbjabatan.setAlignmentX(0.0F);
        cmbjabatan.setAlignmentY(0.0F);
        cmbjabatan.setFocusable(false);
        cmbjabatan.setOpaque(false);
        jLayeredPane2.add(cmbjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 334, 220, 30));

        btnlogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlogin.setContentAreaFilled(false);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 270, 50));

        txtidpengguna.setBackground(new java.awt.Color(211, 211, 211));
        txtidpengguna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtidpengguna.setBorder(null);
        txtidpengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpenggunaActionPerformed(evt);
            }
        });
        txtidpengguna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidpenggunaKeyPressed(evt);
            }
        });
        jLayeredPane2.add(txtidpengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 210, 20));

        txtpassword.setBackground(new java.awt.Color(211, 211, 211));
        txtpassword.setBorder(null);
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        jLayeredPane2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 210, 20));

        ket.setForeground(new java.awt.Color(255, 255, 255));
        ket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Login2.PNG"))); // NOI18N
        jLayeredPane2.add(ket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        btnkeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnkeluar.setContentAreaFilled(false);
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 180, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            AksesLogin(); }
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtidpenggunaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpenggunaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            AksesLogin();
        }
    }//GEN-LAST:event_txtidpenggunaKeyPressed

    private void txtidpenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpenggunaActionPerformed
        // TODO add your handling code here:
        txtidpengguna.setText("");
        //        txtidpengguna.setForeground(Color.RGBtoHSB(0, 0, 0));
    }//GEN-LAST:event_txtidpenggunaActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        AksesLogin();
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
        javax.swing.UIManager.setLookAndFeel(info.getClassName());
        break;
        }
        }
        } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        
        UIManager.put("RootPane.setupButtonVisible", false);
        BeautyEyeLNFHelper.debug =true;
        BeautyEyeLNFHelper.translucencyAtFrameInactive = false;
        try {
            BeautyEyeLNFHelper.launchBeautyEyeLNF();
        } catch (Exception ex) {
            Logger.getLogger(Loginku.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnlogin;
    private javax.swing.JComboBox cmbjabatan;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ket;
    private javax.swing.JTextField txtidpengguna;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
