/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import static Form.MenuUtama.desktopPane;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Arya Wicaksana
 */

public class Pendaftaran extends javax.swing.JInternalFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private String jeniskelamin;
    
public static int idpengguna;
public static String jabatan;

    public static int getIdpengguna() {
        return idpengguna;
    }

    public static String getJabatan() {
        return jabatan;
    }
   

    /**
     * Creates new form Pendaftaran
     */
    
  private void id_pendaftaran_siap(){
          try
       {
            String Sql = "select max(id_pendaftaran) from pendaftaran";
            pst=conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                lbl_id_pendaftaran.setText(rs.getString(1));
                int value1 =  Integer.parseInt(lbl_id_pendaftaran.getText());
                int value2 = value1+1;
                String siap = Integer.toString(value2);
                lbl_id_pendaftaran.setText(siap);
            }
       }
catch (Exception e)
{String p;
        p="1";
    lbl_id_pendaftaran.setText(p);
    System.out.println(e);
}   
}

 
    public Pendaftaran() {
        setLocation(370, 125);
        initComponents();
        this.setSize(675, 405);
       //setLocation(590, 0);
        conn = KoneksiDB.ConnectDb(); 
        id_pendaftaran_siap();
        lbl_id_pendaftar_yang_mendaftar.setText(Pendaftar.lbl_id_pendaftar.getText());
        cb_opsi_sp.setVisible(false);
        lblpengguna.setText("Form ini diisi oleh "+jabatan+" "+idpengguna);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgdenda = new javax.swing.ButtonGroup();
        bgjk = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblnama4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnlanjut = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        cbjenispermohonan = new javax.swing.JComboBox();
        tgl_daftar = new com.toedter.calendar.JDateChooser();
        tgl_jadi = new com.toedter.calendar.JDateChooser();
        lblpengguna = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("Pendaftaran");
        setMinimumSize(new java.awt.Dimension(20, 383));
        setPreferredSize(new java.awt.Dimension(560, 383));

        jPanel4.setPreferredSize(new java.awt.Dimension(570, 455));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tanggal Daftar :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));

        lblnama4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnama4.setText("Jenis Permohonan :");
        jPanel4.add(lblnama4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Jadi :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        btnlanjut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlanjut.setText("Lanjutkan");
        btnlanjut.setEnabled(false);
        btnlanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlanjutActionPerformed(evt);
            }
        });
        jPanel4.add(btnlanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 130, -1));

        btnsimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel4.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, 50));

        cbjenispermohonan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbjenispermohonan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KTP", "Surat Pindah", "Surat Pindah Datang" }));
        cbjenispermohonan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenispermohonanActionPerformed(evt);
            }
        });
        jPanel4.add(cbjenispermohonan, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 101, 180, -1));

        tgl_daftar.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(tgl_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 145, 171, -1));

        tgl_jadi.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(tgl_jadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 200, 258, -1));

        lblpengguna.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblpengguna.setText("nama pengguna yang mengisi form pendaftaran ini");
        jPanel4.add(lblpengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, -1, -1));

        lbl_id_pendaftar_yang_mendaftar.setText("xxxx");
        jPanel4.add(lbl_id_pendaftar_yang_mendaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 308, -1, -1));

        jLabel1.setText("ID Pendaftar :");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 308, -1, -1));

        jLabel4.setFont(new java.awt.Font("SFNS Display", 0, 48)); // NOI18N
        jLabel4.setText("Pendaftaran");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cb_opsi_sp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Antar Kecamatan dalam Satu Kabupaten", "Antar Kab./Kota atau Antar Provinsi" }));
        cb_opsi_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_opsi_spActionPerformed(evt);
            }
        });
        jPanel4.add(cb_opsi_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 230, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID Pendaftaran :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));

        lbl_id_pendaftaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_id_pendaftaran.setText("xxxxx");
        jPanel4.add(lbl_id_pendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 69, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbjenispermohonanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenispermohonanActionPerformed
        // TODO add your handling code here:
       if ((cbjenispermohonan.getSelectedItem() == "Surat Pindah")||(cbjenispermohonan.getSelectedItem() == "Surat Pindah Datang")) {
            cb_opsi_sp.setVisible(true);
            }
        else {
            cb_opsi_sp.setVisible(false);
        }
    }//GEN-LAST:event_cbjenispermohonanActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try
        {
                    
            String Sql = "insert into pendaftaran (id_pendaftaran,jenis_permohonan,tgl_daftar,tgl_jadi,id_pengguna,id_pendaftar) values (?,?,?,?,?,?)";
            pst=conn.prepareStatement(Sql);

            pst.setInt(1, 0);
            pst.setString(2, (String) cbjenispermohonan.getSelectedItem());
            pst.setString(3, ((JTextField)tgl_daftar.getDateEditor().getUiComponent()).getText());
            pst.setString(4, ((JTextField)tgl_jadi.getDateEditor().getUiComponent()).getText());
            pst.setInt(5, idpengguna);
            pst.setInt(6, Integer.parseInt(Pendaftar.lbl_id_pendaftar.getText()));

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan.","[ SUKSES ]",1);
            btnlanjut.setEnabled(true);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Penambahan data ke tabel SQL : Error");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnlanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlanjutActionPerformed
        // TODO add your handling code here:
        if (cbjenispermohonan.getSelectedItem() == "KTP"){
            KTP X = new KTP();
        desktopPane.add(X);
        X.setVisible(true);
        this.setVisible(false);
        }
        else if (cbjenispermohonan.getSelectedItem() == "Surat Pindah") {
            DapatkanId_daftar_kyp y = new DapatkanId_daftar_kyp();
        desktopPane.add(y);
        y.setVisible(true);
        this.setVisible(false);
        }
        else if (cbjenispermohonan.getSelectedItem() == "Surat Pindah Datang") {
            DapatkanId_daftar_kyd z = new DapatkanId_daftar_kyd();
        desktopPane.add(z);
        z.setVisible(true);
        this.setVisible(false);
        }
       
    }//GEN-LAST:event_btnlanjutActionPerformed

    private void cb_opsi_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_opsi_spActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_opsi_spActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgdenda;
    private javax.swing.ButtonGroup bgjk;
    public static javax.swing.JButton btnlanjut;
    private javax.swing.JButton btnsimpan;
    public static final javax.swing.JComboBox cb_opsi_sp = new javax.swing.JComboBox();
    private javax.swing.JComboBox cbjenispermohonan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    public static final javax.swing.JLabel lbl_id_pendaftar_yang_mendaftar = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_id_pendaftaran = new javax.swing.JLabel();
    private javax.swing.JLabel lblnama4;
    private javax.swing.JLabel lblpengguna;
    private com.toedter.calendar.JDateChooser tgl_daftar;
    private com.toedter.calendar.JDateChooser tgl_jadi;
    // End of variables declaration//GEN-END:variables
}
