/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Arya Wicaksana
 */
public class UbahPendSP extends javax.swing.JInternalFrame {
Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
        
private void UpdateTabelSP(){
    try
        {
            String sql = "select id_surat_pindah as 'ID S.P', "
                    + " kode_form as 'Kode Form', no_surat_pindah as 'No.Surat S.P',"
                    + " provinsi as 'Provinsi', kab_kota as 'Kab/Kota',"
                    + " kecamatan as 'Kecamatan', dusun_dukuh_kampung as 'Dusun Dukuh Kampung', "
                    + " desa_kelurahan as 'Desa/Kelurahan', id_dda as 'ID DDA', id_dkp as 'ID DKP', "
                    + " id_pendaftar as 'ID Pendaftar', id_pendaftaran as 'ID Pendaftaran', "
                    + " id_daftar_kyp as 'ID Daftar KYP' from surat_pindah order by id_surat_pindah desc; ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tbl_ubah_spd.setModel(DbUtils.resultSetToTableModel(rs));
        }
catch (Exception e)
{
    JOptionPane.showMessageDialog(null, e);
}
}
    /**
     * Creates new form UbahPendSP
     */
    public UbahPendSP() {
         initComponents();
         setSize(1253, 600);
         conn = KoneksiDB.ConnectDb();
         UpdateTabelSP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ubah_spd = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id_pendaftaran = new javax.swing.JTextField();
        txt_idpendaftar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_simpan_perubahan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_kosongkan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_id_surat_pindah = new javax.swing.JTextField();
        txt_provinsi = new javax.swing.JTextField();
        txt_kode_form = new javax.swing.JTextField();
        txt_no_surat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_kecamatan = new javax.swing.JTextField();
        txt_kab_kota = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_dusun_dukuh_kampung = new javax.swing.JTextField();
        txt_desa_kelurahan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_id_dda = new javax.swing.JTextField();
        txt_id_dkp = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_daftar_kyp = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        tbl_ubah_spd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbl_ubah_spd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ubah_spdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ubah_spd);

        jLabel1.setText("Kode form :");

        jLabel2.setText("ID Pendaftaran :");

        jLabel3.setText("ID Pendaftar :");

        jLabel5.setText("Provinsi :");

        txt_id_pendaftaran.setFocusCycleRoot(true);
        txt_id_pendaftaran.setFocusTraversalPolicyProvider(true);

        jLabel6.setFont(new java.awt.Font("SFNS Display", 0, 36)); // NOI18N
        jLabel6.setText("Ubah Pendaftaran Surat Pindah");

        btn_simpan_perubahan.setText("Simpan Perubahan");
        btn_simpan_perubahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_perubahanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_kosongkan.setText("Kosongkan\nTeks\n");
        btn_kosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kosongkanActionPerformed(evt);
            }
        });

        jLabel7.setText("ID Surat Pindah :");

        jLabel8.setText("No. Surat :");

        txt_provinsi.setFocusCycleRoot(true);
        txt_provinsi.setFocusTraversalPolicyProvider(true);

        txt_kode_form.setFocusCycleRoot(true);
        txt_kode_form.setFocusTraversalPolicyProvider(true);

        txt_no_surat.setFocusCycleRoot(true);
        txt_no_surat.setFocusTraversalPolicyProvider(true);

        jLabel4.setText("Kab/Kota :");

        jLabel9.setText("Kecamatan :");

        txt_kecamatan.setFocusCycleRoot(true);
        txt_kecamatan.setFocusTraversalPolicyProvider(true);

        jLabel10.setText("Dusun/Dukuh/Kampung :");

        jLabel11.setText("Desa/Kelurahan :");

        txt_dusun_dukuh_kampung.setFocusCycleRoot(true);
        txt_dusun_dukuh_kampung.setFocusTraversalPolicyProvider(true);

        txt_desa_kelurahan.setFocusCycleRoot(true);
        txt_desa_kelurahan.setFocusTraversalPolicyProvider(true);

        jLabel12.setText("ID DKP :");

        jLabel13.setText("ID DDA :");

        txt_id_dkp.setFocusCycleRoot(true);
        txt_id_dkp.setFocusTraversalPolicyProvider(true);

        jLabel14.setText("ID Daftar KYP :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_simpan_perubahan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_kosongkan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_provinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_no_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id_surat_pindah, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_kode_form, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(93, 93, 93)
                                        .addComponent(txt_kab_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_desa_kelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_dusun_dukuh_kampung, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_kecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(681, 681, 681)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel12))))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id_pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id_dda, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_idpendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id_dkp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_daftar_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id_surat_pindah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_kode_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_kab_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_kecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_no_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txt_dusun_dukuh_kampung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_provinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txt_desa_kelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id_dda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(txt_daftar_kyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_dkp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_idpendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_id_pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simpan_perubahan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_kosongkan)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ubah_spdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ubah_spdMouseClicked
        // TODO add your handling code here:
         btn_simpan_perubahan.setText("Simpan Perubahan");

        try{
            int row = tbl_ubah_spd.getSelectedRow();
            String Table_click = (tbl_ubah_spd.getModel().getValueAt(row, 0).toString());
            String sql= "select * from surat_pindah where id_surat_pindah='"+Table_click+"' ";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()) {
                String add1= rs.getString("id_surat_pindah");
                txt_id_pendaftaran.setText(add1);
                
                String add2= rs.getString("kode_form");
                txt_kode_form.setText(add2);

                String add3= rs.getString("no_surat_pindah");
                txt_no_surat.setText(add3);

                String add4= rs.getString("provinsi");
                txt_provinsi.setText(add4);

                String add5= rs.getString("kab_kota");
                txt_kab_kota.setText(add5);
                
                String add6= rs.getString("kecamatan");
                txt_kecamatan.setText(add6);
                
                String add7= rs.getString("dusun_dukuh_kampung");
                txt_dusun_dukuh_kampung.setText(add7);
                
                String add8= rs.getString("desa_kelurahan");
                txt_desa_kelurahan.setText(add8);
                
                String add9= rs.getString("id_dda");
                txt_id_dda.setText(add9);
                
                String add10= rs.getString("id_ddt");
                txt_id_dkp.setText(add10);
                
                String add11= rs.getString("id_pendaftar");
                txt_idpendaftar.setText(add11);
                
                String add12= rs.getString("id_pendaftaran");
                txt_id_pendaftaran.setText(add12);
                
                String add13= rs.getString("id_daftar_kyd");
                txt_daftar_kyp.setText(add13);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbl_ubah_spdMouseClicked

    private void btn_simpan_perubahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_perubahanActionPerformed
        // TODO add your handling code here:
        try
        {
        int value1= Integer.parseInt(txt_id_surat_pindah.getText());
        String value2= txt_kode_form.getText();
        String value3= txt_no_surat.getText();
        String value4= txt_provinsi.getText();
        String value5= txt_kab_kota.getText();
        String value6= txt_kecamatan.getText();
        String value7= txt_dusun_dukuh_kampung.getText();
        String value8= txt_desa_kelurahan.getText();
        int value9= Integer.parseInt(txt_id_dda.getText());
        int value10= Integer.parseInt(txt_id_dkp.getText());
        int value11= Integer.parseInt(txt_idpendaftar.getText());
        int value12= Integer.parseInt(txt_id_pendaftaran.getText());
        int value13= Integer.parseInt(txt_daftar_kyp.getText());
        
        String sql = "UPDATE surat_pindah SET id_surat_pindah='"+value1+"',"
                + "kode_form='"+value2+"',no_surat_pindah_datang='"+value3+"',provinsi='"+value4+"',"
                + "kab_kota='"+value5+"',kecamatan='"+value6+"',dusun_dukuh_kampung='"+value7+"',"
                + "desa_kelurahan='"+value8+"',id_dda='"+value9+"',id_dkp='"+value10+"',"
                + "id_pendaftar='"+value11+"',id_pendaftaran='"+value12+"',id_daftar_kyp='"+value13+"' "
                + "WHERE id_surat_pindah='"+value1+"'";
        pst=conn.prepareStatement(sql);
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "Data berhasil diubah.","[ SUKSES ]",1);
        UpdateTabelSP();
        
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_simpan_perubahanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        { 
        String ObjButtons[] = {"Ya","Tidak"};
        int PromptResult = JOptionPane.showOptionDialog(null,"Apakah Anda ingin menghapus data yang anda pilih?","[ PENTING ]",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(PromptResult==JOptionPane.YES_OPTION)
        {
            String sql="delete from surat_pindah where id_surat_pindah= ?";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_id_surat_pindah.getText());
                pst.execute();

                JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk menghapus data ini?","[ KONFIRMASI ]",JOptionPane.YES_NO_OPTION);
                UpdateTabelSP();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            }
        else{};
    
    }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_kosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kosongkanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_kosongkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kosongkan;
    private javax.swing.JButton btn_simpan_perubahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ubah_spd;
    private javax.swing.JTextField txt_daftar_kyp;
    private javax.swing.JTextField txt_desa_kelurahan;
    private javax.swing.JTextField txt_dusun_dukuh_kampung;
    private javax.swing.JTextField txt_id_dda;
    private javax.swing.JTextField txt_id_dkp;
    private javax.swing.JTextField txt_id_pendaftaran;
    private javax.swing.JTextField txt_id_surat_pindah;
    private javax.swing.JTextField txt_idpendaftar;
    private javax.swing.JTextField txt_kab_kota;
    private javax.swing.JTextField txt_kecamatan;
    private javax.swing.JTextField txt_kode_form;
    private javax.swing.JTextField txt_no_surat;
    private javax.swing.JTextField txt_provinsi;
    // End of variables declaration//GEN-END:variables
}
