/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Arya Wicaksana
 */
public class UbahPetugas extends javax.swing.JInternalFrame {
Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    
 private void buatnomor(){
        String sql = "select max(id_pengguna) from pengguna";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()){
                int a = rs.getInt(1);
                txt_idpengguna.setText(""+ Integer.toString(a+1));
            }
           
        }catch (Exception e){
            System.out.println(""+ e.getMessage());
        }
 }


private void req() {
txt_password.requestFocus();
}

    
private void UpdateTabel(){
    try
        {
            String sql = "select * from pengguna;";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tblpetugasadmin.setModel(DbUtils.resultSetToTableModel(rs));
        }
catch (Exception e)
{
    JOptionPane.showMessageDialog(null, e);
}
}

    public UbahPetugas() {
        initComponents();
         conn = KoneksiDB.ConnectDb();
         UpdateTabel();
         buatnomor();
         //txt_idpengguna.setFocusable(false);
         txt_password.isFocusable();
         txt_password.requestFocusInWindow();
         txt_password.grabFocus();
         txt_password.addFocusListener(null);
         req();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblpetugasadmin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_idpengguna = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_nama_admin = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbjabatanpetugasadmin = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Ubah Data Admin atau Petugas");
        setNextFocusableComponent(txt_password);

        tblpetugasadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblpetugasadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpetugasadminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpetugasadmin);

        jLabel1.setText("ID Pengguna :");

        jLabel2.setText("Password :");

        jLabel3.setText("Nama :");

        jLabel4.setText("No HP :");

        jLabel5.setText("Jabatan :");

        txt_password.setFocusCycleRoot(true);
        txt_password.setFocusTraversalPolicy(null);
        txt_password.setFocusTraversalPolicyProvider(true);

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        jLabel6.setText("Pengguna Sistem");

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Kosongkan\nTeks\n");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cbjabatanpetugasadmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Petugas", "Admin" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_nama_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(txt_nohp, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(txt_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbjabatanpetugasadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nama_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbjabatanpetugasadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblpetugasadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpetugasadminMouseClicked
        // TODO add your handling code here:
        try{
            int row = tblpetugasadmin.getSelectedRow();
            String Table_click = (tblpetugasadmin.getModel().getValueAt(row, 0).toString());
            String sql= "select * from pengguna where id_pengguna='"+Table_click+"' ";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()) {
                String add1= rs.getString("id_pengguna");
                txt_idpengguna.setText(add1);
                String add2= rs.getString("password");
                txt_password.setText(add2);
                String add3= rs.getString("nama_admin");
                txt_nama_admin.setText(add3);
                String add4= rs.getString("no_hp");
                txt_nohp.setText(add4);
                String add5= rs.getString("jabatan");
                cbjabatanpetugasadmin.setSelectedItem(add5);
            }
      }
        catch(Exception e){
        }
    }//GEN-LAST:event_tblpetugasadminMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        try
        {
            String Sql = "insert into pengguna (id_pengguna,password,nama_admin,no_hp,jabatan) values (?,?,?,?,?)";
            pst=conn.prepareStatement(Sql);

            pst.setInt(1, Integer.parseInt(txt_idpengguna.getText()));
            pst.setString(2, txt_password.getText());
            pst.setString(3, txt_nama_admin.getText());
            pst.setString(4, txt_nohp.getText());
            pst.setString(5, (String) cbjabatanpetugasadmin.getSelectedItem());
                                    
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan.","[ SUKSES ]",1);
            UpdateTabel();
            buatnomor();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Penambahan data ke tabel SQL : Error");
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btntambahActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String value1= txt_idpengguna.getText();
            String value2= txt_password.getText();
            String value3= txt_nama_admin.getText();
            String value4= txt_nohp.getText();
            String value5= (String) cbjabatanpetugasadmin.getSelectedItem();
            
            String sql = "update pengguna set id_pengguna='"+value1+"' ,password='"+value2+"' ,nama_admin='"+value3+"' ,no_hp='"+value4+"' ,jabatan='"+value5+"' where id_pengguna='"+value1+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil diubah.","[ SUKSES ]",1);
            UpdateTabel();
            buatnomor();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "eror bro");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        { 
        String ObjButtons[] = {"Ya","Tidak"};
        int PromptResult = JOptionPane.showOptionDialog(null,"Apakah Anda ingin menghapus data yang anda pilih?","[ PENTING ]",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(PromptResult==JOptionPane.YES_OPTION)
        {
        String sql="delete from pengguna where id_pengguna= ?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_idpengguna.getText());
            pst.execute();
            
            JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk menghapus data ini?","[ KONFIRMASI ]",JOptionPane.YES_NO_OPTION);
            UpdateTabel();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        else{};
        
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txt_idpengguna.setText("");
        txt_password.setText("");
        txt_nama_admin.setText("");
        txt_nohp.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox cbjabatanpetugasadmin;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpetugasadmin;
    private javax.swing.JTextField txt_idpengguna;
    private javax.swing.JTextField txt_nama_admin;
    private javax.swing.JTextField txt_nohp;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
